Analysis Code
vidhishanair/structured_summarizer pull request #5
Opened 2019-12-20 18:13 UTC by artidoro

Please feel free to push directly to this branch if you want to make any modifications to this PR (or comment here and I'll address it).

2019-12-22 18:10 UTC, vidhishanair commented on analysis.py
> -import os
Why delete this file? It might clash with my code. Leave the contents as is?

2019-12-22 18:19 UTC, vidhishanair commented on main.py
> +    parser.add_argument('--minimum_seq', type=int, default=3, help='Min sequence len')
What is this and why?

2019-12-22 18:20 UTC, vidhishanair commented on scripts/decode.sh
>  #Namespace(L1_structure_penalty=False, autoencode=False, is_coverage=True, pointer_gen=True, reload_path=None, reload_pretrained_clf_path='log/token_sent_level_tag/model/model_455000_1555707099', sav
Make a separate file for this.

2019-12-22 18:21 UTC, vidhishanair requested changes
Please check the comments :)

2019-12-23 11:19 UTC, artidoro commented on main.py
> +    parser.add_argument('--minimum_seq', type=int, default=3, help='Min sequence len')
It was something I was working on to do increasing sequence length, but I'll remote it. Thank you for catching it!

2019-12-23 11:22 UTC, artidoro commented on analysis.py
> -import os
I split the file into `analysis_summary.py` and `analaysis_tree.py`. It made sense to keep that code separate. It should not clash with your code (you will find the same functions in the other file). I'll make sure that we can see the diff on this file as a rename and modify instead of delete and create new file.

2019-12-23 11:23 UTC, artidoro commented on scripts/decode.sh
>  #Namespace(L1_structure_penalty=False, autoencode=False, is_coverage=True, pointer_gen=True, reload_path=None, reload_pretrained_clf_path='log/token_sent_level_tag/model/model_455000_1555707099', sav
Will do! Thanks

2019-12-24 19:18 UTC, vidhishanair commented on analysis.py
> +    sum_tok = nlp(summary)
So my understanding is that the summary is one sentence per line. So we might not need to tokenize if it's just for sentence splitting.

2019-12-24 23:35 UTC, vidhishanair approved these changes

2019-12-24 23:35 UTC, merged